import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/Navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="lg:flex min-h-screen">
        <div className="lg:w-[300px]">
          {" "}
          {/* fixed sidebar width */}
          <Navigation />
        </div>
        <main className="flex-1">
          {" "}
          {/* main content takes remaining space */}
          {children}
        </main>
      </body>
    </html>
  );
}
