import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col lg:flex-row min-h-screen overflow-hidden">
        {/* Sidebar Navigation */}

        <Navigation />

        {/* Main content scrollable */}
        <main className="flex-1 overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
