import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { GlobalDataProvider } from "@/components/context/GlobalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#F8F4F0]">
      <body className="flex flex-col lg:flex-row min-h-screen overflow-hidden">
        {/* Sidebar Navigation */}
        <Navigation />

        {/* Main content scrollable */}
        <GlobalDataProvider>
          <main className="flex-1 overflow-y-auto">{children}</main>
        </GlobalDataProvider>
      </body>
    </html>
  );
}
